# Generated by Django 4.0.6 on 2023-03-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_api', '0002_alter_filemodel_file_fileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='columns',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
